### ISSUE TITLE
Add the ability to display the listening status

### ISSUE THREAD

**Issue by chicco-carone** [Senophyx/Discord-RPC#28] opened 2024-04-29 14:01 UTC
For some discord applications like spotify and in general media consumption discord has the abilty to display "is listening/watching" with a progress bar and albums/cover art. I can't seem to find a way to recreate this by using this library or the javascript one.

**Comment by pazkero** [comment] 2024-05-01 19:51
For that, you need to change the [ActivityType](https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum)

As far as I know, you cannot set this with RPC. You need the [GameSDK](https://discord.com/developers/docs/game-sdk/getting-started) and I'm not aware of any way to use it with Python.

**Comment by Senophyx** [comment] 2024-05-02 01:13
> For that, you need to change the [ActivityType](https://discord.com/developers/docs/game-sdk/activities#data-models-activitytype-enum)
> 
> As far as I know, you cannot set this with RPC. You need the [GameSDK](https://discord.com/developers/docs/game-sdk/getting-started) and I'm not aware of any way to use it with Python.

Thank you so much Pazkero for the reply.

Yes, I've looked for references about RPC activities other than "playing" but there are no implementation examples either in Python or other programming languages ​​(for standalone programs without using GameSDK).
Therefore this feature will not be implemented in the near future until Discord makes suitable documentation or there are examples from other people.

**Comment by fixator10** [comment] 2024-08-20 09:27
You just need to add "type" field to activity object
Adding `"type": 2,` after [this line](https://github.com/Senophyx/Discord-RPC/blob/875eb05f84ffab4543ecca89d3af1de95fc111df/discordrpc/presence.py#L68)
Produces this RPC:
![Listening to <AppName>](https://moeka.is-a-good-waifu.com/74oEoHL.png)

Docs: 
https://discord.com/developers/docs/rich-presence/using-with-the-embedded-app-sdk#setactivity-fields
https://discord.com/developers/docs/topics/gateway-events#activity-object-activity-types

**Comment by Senophyx** [comment] 2024-08-21 07:03
Thank you @fixator10 for the solution.

Yes, i can confirm this Activity Type works on current code of Discord-RPC. And I will implement this feature in the next version of Discord-RPC (`5.1`). However, I still cannot implement Activity Type `1` (streaming) and `4` (custom). But I will still release version `5.1` by not allowing using Activity Type `1` and `4` until this issue is fixed in the future.

**Comment by Senophyx** [comment] 2024-08-21 07:37
Added to the main code ([#cb0806d](https://github.com/Senophyx/Discord-RPC/commit/cb0806df120fe78fdb50e4dd1b1d8faf1fbd4185)).
> This issue will be closed again and will be updated when the Activity Types 1 and 4 issues are fixed.

**Closed by Senophyx** 2024-08-21 07:37 UTC
Labels: enhancement, on testing

**Comment by chicco-carone** [comment] 2024-09-17 15:34
> Added to the main code ([#cb0806d](https://github.com/Senophyx/Discord-RPC/commit/cb0806df120fe78fdb50e4dd1b1d8faf1fbd4185)).
> 
> > This issue will be closed again and will be updated when the Activity Types 1 and 4 issues are fixed.

@Senophyx i tried to create a listening status with the library which works fine but if you use the listening status there is no way to set the timebar with the progress for the listening status or a way to set the album image to be from an url or a file but only the image method that uses the one from the developer page which is a fixed image.

**Comment by Senophyx** [comment] 2024-09-19 01:35
> if you use the listening status there is no way to set the timebar with the progress for the listening status

just add `ts_start` and `ts_end` to add the time bar.
![image](https://github.com/user-attachments/assets/063950a3-7a1f-4e8b-84dd-9f97b05c3869)
```py
import discordrpc
from discordrpc import utils

rpc = discordrpc.RPC(app_id=123456789)

rpc.set_activity(
      state="A super simple rpc",
      details="simple RPC",
      act_type=2,
      ts_start=utils.timestamp,
      ts_end=1726723833
    )

# Required if you only run Discord RPC on this file or current instance.
rpc.run()
```

> a way to set the album image to be from an url or a file

i think you can't because you have to upload it first through the developer page.

**Comment by Senophyx** [comment] 2024-09-19 01:49
@all-contributors please add @fixator10 for doc
